param(
    [switch]$Force,
    [switch]$Commit
)

function Write-Log($msg) { Write-Host "[gitinit] $msg" }

# Initialize git repository if needed
if (-not (Test-Path -Path .git -PathType Container)) {
    Write-Log "No git repo found — running 'git init'"
    git init | Out-Null
} else {
    Write-Log "Git repository already initialized"
}

$gitignorePath = ".gitignore"

$baseIgnore = @'
# Python virtual environments
venv/
env/
.venv/
VENV/

# Byte-compiled / optimized / DLL files
__pycache__/
*.py[cod]
*$py.class

# Distribution / packaging
build/
dist/
*.egg-info/
pip-wheel-metadata/

# Installer logs
pip-delete-this-directory.txt

# Editor directories
.vscode/

# OS files
.DS_Store
Thumbs.db
'@

if (Test-Path $gitignorePath) {
    if (-not $Force) {
        Write-Log "A .gitignore already exists. Backing up to .gitignore.bak"
        Copy-Item -Path $gitignorePath -Destination "$gitignorePath.bak" -Force
    }
}

Write-Log "Writing base .gitignore"
Set-Content -Path $gitignorePath -Value $baseIgnore -Encoding UTF8

# Add explicit ignores for common site-packages locations inside venvs
@"
# Ignore installed packages inside virtualenv
venv/**/site-packages/
venv/**/dist-packages/
.venv/**/site-packages/
.venv/**/dist-packages/
"@ | Add-Content -Path $gitignorePath -Encoding UTF8

# If requirements.txt exists, attempt to add patterns to ignore installed packages
if (Test-Path "requirements.txt") {
    Write-Log "Found requirements.txt — parsing package names to extend .gitignore"
    $lines = Get-Content requirements.txt | ForEach-Object { $_.Trim() } | Where-Object { $_ -and -not ($_ -like '#*') }
    foreach ($line in $lines) {
        # Extract package name before any version specifier or extras
        if ($line -match '^[A-Za-z0-9_.+-]+') {
            $pkg = $Matches[0]
            $pkgUnderscore = $pkg -replace '-', '_'
            "# Ignore installed package: $pkg" | Add-Content -Path $gitignorePath -Encoding UTF8
            "venv/**/$pkg/" | Add-Content -Path $gitignorePath -Encoding UTF8
            "venv/**/$pkgUnderscore/" | Add-Content -Path $gitignorePath -Encoding UTF8
            ".venv/**/$pkg/" | Add-Content -Path $gitignorePath -Encoding UTF8
            ".venv/**/$pkgUnderscore/" | Add-Content -Path $gitignorePath -Encoding UTF8
        }
    }
}

Write-Log ".gitignore created at: $gitignorePath"

if ($Commit) {
    if (git rev-parse --is-inside-work-tree 2>$null) {
        Write-Log "Staging .gitignore"
        git add $gitignorePath
        try {
            git commit -m "chore: add .gitignore (generated by gitinit)" | Out-Null
            Write-Log "Committed .gitignore"
        } catch {
            Write-Log "Commit failed — make sure git user.name/user.email are configured or commit manually"
        }
    }
}

Write-Log "Done. Review .gitignore and adjust patterns if needed."
